apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /
    # UPDATE ANNOTATION
spec:
  ingressClassName: nginx
  rules:
  -  http:
        paths:
          - path: /
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name:  story-service
                port:
                  number: 80