name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: main
       - name: Building Docker Node-Goat Image
         run: docker-compose build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.6.1
         with:
           # Target URL
           target: "http://localhost:1313"
           fail_action: false
           rules_file_name: '.zap/rules.tsv'
           cmd_options: '-a'
